import { Injectable, computed, inject, resource, signal } from '@angular/core';
import { stableResourceValue } from '../../../core/signals/stable-resource';
import { TriggerService } from '../trigger.service';
import { TradeSettingsService } from '../trade-settings.service';
import { MarketTimeService } from '../market-time.service';
import { norm } from '../../../core/tokens/token-normalize';
import { BinaryMarket, BinaryOptionsReadService, BinaryOrder } from '../../onchain/contracts/binary-options-read.service';
import { BinaryOptionsFormatService } from './binary-options-format.service';
export type BinaryMarketRow={marketKey:string;market:BinaryMarket;orderCount:bigint;myOrderCount:bigint;totalPayout:bigint};
export type BinaryPositionRow={marketKey:string;market:BinaryMarket;holderClaimable:bigint;writerMargin:bigint;openInterest:bigint;settlementStatus:string;claimHint:string;reclaimHint:string;sellHolderHint:string;buyHint:string;writeHint:string;canClaim:boolean;canReclaim:boolean;canSellHolder:boolean;canBuy:boolean;canWrite:boolean;claimLabel:string;};
export type BinaryLadderRow={orderId:bigint;side:'bid'|'ask';isMine:boolean;order:BinaryOrder};
@Injectable({providedIn:'root'})
export class BinaryOptionsOrderBookStore{
 private readonly reads=inject(BinaryOptionsReadService); private readonly trigger=inject(TriggerService); private readonly settings=inject(TradeSettingsService); private readonly marketTime=inject(MarketTimeService); private readonly fmt=inject(BinaryOptionsFormatService);
 readonly selectedMarketKey=signal<string|null>(null); readonly activeView=signal<'markets'|'orders'|'positions'|'my-orders'>('markets'); readonly selectedPositionMarketKey=signal<string|null>(null); readonly marketFetchLimit=signal(100); readonly marketOffset=signal(0); readonly marketLimit=signal(25); readonly marketSearch=signal(''); readonly marketsWithMyOrdersOnly=signal(false); readonly myOrdersOnly=signal(false);
 tokenLabel=(a:string)=>this.fmt.tokenLabel(a); formatEth=(v:bigint)=>this.fmt.formatEth(v); formatStrike=(v:bigint)=>this.fmt.formatStrike(v); formatProbability=(v:bigint)=>this.fmt.formatProbability(v); formatPricePerEth=(v:bigint)=>this.fmt.formatPricePerEth(v); condition=(t:number,b:string,s:bigint)=>this.fmt.condition(t,b,s);
 readonly activeAccount=computed(()=>norm(this.settings.selectedAccountId()??''));
 private readonly fillAmounts=signal<Record<string,string>>({}); fillAmountByOrderId(id:bigint):string{return this.fillAmounts()[id.toString()]??''} setFillAmount(id:bigint,v:string):void{const key=id.toString(); const value=String(v??''); this.fillAmounts.update(current=>({...current,[key]:value}))}
 private readonly _marketsRes=resource<BinaryMarketRow[],{tick:number;limit:number;account:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),limit:this.marketFetchLimit(),account:this.activeAccount()}),loader:async({params})=>{const count=Number(await this.reads.getMarketCount()); const rows:BinaryMarketRow[]=[]; const mine=(o:BinaryOrder)=>!!params.account&&norm(o.user)===params.account; for(let i=0;i<Math.min(count,params.limit);i++){const k=await this.reads.getMarketKeyAt(i); if(!k)continue; const market=await this.reads.getMarket(k); if(!market||!market.active)continue; const [bids,asks]=await Promise.all([this.reads.getOpenOrders(k,true),this.reads.getOpenOrders(k,false)]); const orders=[...bids,...asks]; rows.push({marketKey:k,market,orderCount:BigInt(orders.length),myOrderCount:BigInt(orders.filter(mine).length),totalPayout:orders.reduce((sum,o)=>sum+o.payoutAmount,0n)})} rows.sort((a,b)=>Number(b.orderCount-a.orderCount)); return rows}});
 private readonly _stableMarkets=stableResourceValue(()=>this._marketsRes.value(), [] as BinaryMarketRow[], {resetKey:()=>this.marketFetchLimit()}); readonly activeMarkets=computed(()=>this._stableMarkets()); readonly filteredMarkets=computed(()=>{const q=this.marketSearch().trim().toLowerCase(); const onlyMine=this.marketsWithMyOrdersOnly(); const positionMarkets=new Set(this.myPositions().map((p)=>String(p.marketKey??'').toLowerCase())); let list=this.activeMarkets().filter((m)=>this.marketTime.hasOpenOptionWindow(m.market)||positionMarkets.has(String(m.marketKey??'').toLowerCase())||(m.myOrderCount??0n)>0n); if(q){list=list.filter((m)=>[this.condition(m.market.optionType,this.tokenLabel(m.market.baseToken),m.market.strikePrice),m.marketKey,this.tokenLabel(m.market.baseToken)].some((v)=>String(v??'').toLowerCase().includes(q)));} if(onlyMine){list=list.filter((m)=>(m.myOrderCount??0n)>0n);} return list;}); readonly visibleMarkets=computed(()=>{const start=Math.max(0,Number(this.marketOffset()||0)); const limit=Math.max(1,Number(this.marketLimit()||25)); return this.filteredMarkets().slice(start,start+limit);}); selectMarket(k:string){this.selectedMarketKey.set(String(k??'').toLowerCase())} clearMarket(){this.selectedMarketKey.set(null)} readonly selectedMarket=computed(()=>this.activeMarkets().find(m=>m.marketKey===this.selectedMarketKey())??null);
 private readonly _ladderRes=resource<{bids:BinaryLadderRow[];asks:BinaryLadderRow[]},{tick:number;marketKey:string|null;account:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),marketKey:this.selectedMarketKey(),account:this.activeAccount()}),loader:async({params})=>{if(!params.marketKey)return{bids:[],asks:[]}; const [br,ar]=await Promise.all([this.reads.getOpenOrders(params.marketKey,true),this.reads.getOpenOrders(params.marketKey,false)]); const mine=(o:BinaryOrder)=>!!params.account&&norm(o.user)===params.account; return {bids:br.map(order=>({orderId:order.orderId,side:'bid' as const,isMine:mine(order),order})).sort((a,b)=>Number(b.order.askPrice-a.order.askPrice)), asks:ar.map(order=>({orderId:order.orderId,side:'ask' as const,isMine:mine(order),order})).sort((a,b)=>Number(a.order.askPrice-b.order.askPrice))}}});
 private readonly _stableLadder=stableResourceValue(()=>this._ladderRes.value(), {bids: [] as BinaryLadderRow[], asks: [] as BinaryLadderRow[]}, {resetKey:()=>this.selectedMarketKey()}); readonly bids=computed(()=>{const rows=this._stableLadder().bids; return this.myOrdersOnly()?rows.filter((r)=>r.isMine):rows}); readonly asks=computed(()=>{const rows=this._stableLadder().asks; return this.myOrdersOnly()?rows.filter((r)=>r.isMine):rows}); readonly bestBid=computed(()=>this.bids()[0]?.order.askPrice??null); readonly bestAsk=computed(()=>this.asks()[0]?.order.askPrice??null); readonly spread=computed(()=>{const b=this.bestBid(); const a=this.bestAsk(); if(b===null||a===null||a<b)return null; return a-b});
 private readonly _positionsRes=resource<BinaryPositionRow[],{tick:number;account:string;marketHash:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),account:this.activeAccount(),marketHash:this.activeMarkets().map(m=>m.marketKey).join('|')}),loader:async({params})=>{if(!params.account)return[]; const rows:BinaryPositionRow[]=[]; const now=await this.reads.latestTimestamp(); for(const m of this.activeMarkets()){const [h,w,oi]=await Promise.all([this.reads.getHolderClaimablePayout(m.marketKey,params.account),this.reads.getWriterAvailableMargin(m.marketKey,params.account),this.reads.getMarketOpenInterest(m.marketKey)]); if(h>0n||w>0n){const status=this.settlementStatus(m.market); const settled=!!m.market.settled; const marketOpen=!settled&&m.market.active&&now<m.market.expiry; const canClaim=h>0n&&settled; const canReclaim=w>0n&&settled&&oi===0n; const canSellHolder=h>0n&&marketOpen; const canBuy=marketOpen; const canWrite=marketOpen; const claimLabel=m.market.settled&&this.isITM(m.market)?'Claim payout':'Clear position'; const claimHint=h<=0n?'No holder position':!settled?'Available after oracle settlement':this.isITM(m.market)?'In the money: claim ETH payout':'Out of the money or equal: clears holder position with zero payout'; const reclaimHint=w<=0n?'No writer position':!settled?'Available after oracle settlement':oi>0n?'Waiting for holders to claim/clear outstanding payout':'Writer margin can be reclaimed'; const buyHint=canBuy?'Buy additional holder payout in this market':'Market is expired, settled, or closed'; const writeHint=canWrite?'Write fresh payout and lock ETH margin':'Market is expired, settled, or closed'; const sellHolderHint=h<=0n?'No holder payout to sell':canSellHolder?'Sell existing holder payout before market expiry':'Holder payout can only be sold before settlement/expiry'; rows.push({marketKey:m.marketKey,market:m.market,holderClaimable:h,writerMargin:w,openInterest:oi,settlementStatus:status,claimHint,reclaimHint,sellHolderHint,buyHint,writeHint,canClaim,canReclaim,canSellHolder,canBuy,canWrite,claimLabel})}} return rows}});
 
 private readonly _myOrdersRes=resource<BinaryLadderRow[],{tick:number;account:string;markets:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),account:this.activeAccount(),markets:this.activeMarkets().map(m=>m.marketKey).join('|')}),loader:async({params})=>{if(!params.account)return[]; const mine=(o:BinaryOrder)=>norm(o.user)===params.account; const rows:BinaryLadderRow[]=[]; for(const m of this.activeMarkets()){const [bids,asks]=await Promise.all([this.reads.getOpenOrders(m.marketKey,true),this.reads.getOpenOrders(m.marketKey,false)]); rows.push(...bids.filter(mine).map(order=>({orderId:order.orderId,side:'bid' as const,isMine:true,order}))); rows.push(...asks.filter(mine).map(order=>({orderId:order.orderId,side:'ask' as const,isMine:true,order})))} rows.sort((a,b)=>Number((b.orderId??0n)-(a.orderId??0n))); return rows}});
 private readonly _stableMyOrders=stableResourceValue(()=>this._myOrdersRes.value(), [] as BinaryLadderRow[], {resetKey:()=>this.activeAccount()}); readonly myOrders=computed(()=>this._stableMyOrders());
 private readonly _stablePositions=stableResourceValue(()=>this._positionsRes.value(), [] as BinaryPositionRow[], {resetKey:()=>this.activeAccount()}); readonly myPositions=computed(()=>this._stablePositions()); selectPosition(k:string){this.selectedPositionMarketKey.set(String(k??'').toLowerCase())} clearSelectedPosition(){this.selectedPositionMarketKey.set(null)} readonly selectedPosition=computed(()=>this.myPositions().find(p=>p.marketKey===this.selectedPositionMarketKey())??null);
 private isITM(m:BinaryMarket):boolean{return m.settled&&(m.optionType===0?m.settlementPrice>m.strikePrice:m.settlementPrice<m.strikePrice)}
 private settlementStatus(m:BinaryMarket):string{if(!m.settled)return 'Pending settlement'; if(m.settlementPrice===m.strikePrice)return 'Equal strike: no payout'; return this.isITM(m)?`${m.optionType===0?'Above':'Below'} won`:`${m.optionType===0?'Above':'Below'} lost`}
}
