import { Injectable, inject } from '@angular/core';
import { ethers } from 'ethers';
import { WalletConnectService } from '../../../wallet/wallet-connect.service';
import { getContractAddress } from '../../../contracts/contract-registry';
import { CONTRACT_ABIS } from '../../../contracts/generated';

export type MarginMarket = { initialized:boolean; active:boolean; settled:boolean; optionType:number; ticker:string; oracle:string; baseToken:string; paymentToken:string; oraclePriceDecimals:number; paymentTokenDecimals:number; strikePrice:bigint; strikeIncrement:bigint; expiry:bigint; collateralBps:bigint; multiplier:bigint; settlementPrice:bigint; totalSize:bigint; totalClaimed:bigint; totalWriterMargin:bigint; totalPaidOut:bigint; openInterest?:bigint; latestOraclePrice?:bigint; latestOraclePriceDecimals?:number; latestOracleTimestamp?:bigint; latestOracleStatus?:number };
export type MarginHolderPosition = { size: bigint; claimed: bigint; reserved: bigint };
export type MarginWriterPosition = { size: bigint; allocated: bigint; lockedMargin: bigint; paidOut: bigint; reserved: bigint };
export type MarginOrder = { orderId:bigint; user:string; marketKey:string; intent:number; size:bigint; filled:bigint; askPrice:bigint; expiry:bigint; timestamp:bigint; active:boolean; feeToken?:string };
function bi(x:any):bigint{try{return typeof x==='bigint'?x:BigInt(x?.toString?.()??'0')}catch{return 0n}}
function addr(x:any):string{return String(x??'').toLowerCase()}
@Injectable({providedIn:'root'})
export class MarginOptionsReadService{
 private readonly wallet=inject(WalletConnectService); readonly marginContractAddress=getContractAddress('MarginOptionContract'); readonly orderBookAddress=getContractAddress('MarginOptionsOrderBook');
 private async mc():Promise<any|null>{const p=await this.wallet.getEthersProvider(); return p?new ethers.Contract(this.marginContractAddress,CONTRACT_ABIS.MarginOptionContract,p) as any:null}
 private async ob():Promise<any|null>{const p=await this.wallet.getEthersProvider(); return p?new ethers.Contract(this.orderBookAddress,CONTRACT_ABIS.MarginOptionsOrderBook,p) as any:null}
 private async pm():Promise<any|null>{const p=await this.wallet.getEthersProvider(); return p?new ethers.Contract(getContractAddress('PriceManager'),CONTRACT_ABIS.PriceManager,p) as any:null}
 private mapMarket(m:any):MarginMarket|null{if(!m)return null; const initialized=Boolean(m.initialized??m[0]); if(!initialized)return null; return {initialized,active:Boolean(m.active??m[1]),settled:Boolean(m.settled??m[2]),optionType:Number(m.optionType??m[3]??0),ticker:String(m.ticker??m[4]??''),oracle:addr(m.oracle??m[5]),baseToken:addr(m.baseToken??m[6]),paymentToken:addr(m.paymentToken??m[7]),oraclePriceDecimals:Number(m.oraclePriceDecimals??m[8]??18),paymentTokenDecimals:Number(m.paymentTokenDecimals??m[9]??18),strikePrice:bi(m.strikePrice??m[10]),strikeIncrement:bi(m.strikeIncrement??m[11]),expiry:bi(m.expiry??m[12]),collateralBps:bi(m.collateralBps??m[13]),multiplier:bi(m.multiplier??m[14]),settlementPrice:bi(m.settlementPrice??m[15]),totalSize:bi(m.totalSize??m[16]),totalClaimed:bi(m.totalClaimed??m[17]),totalWriterMargin:bi(m.totalWriterMargin??m[18]),totalPaidOut:bi(m.totalPaidOut??m[19])}}
 private mapOrder(o:any,mk?:string):MarginOrder|null{if(!o)return null; const user=addr(o.user??o[1]); if(!user||user===ethers.ZeroAddress.toLowerCase())return null; const size=bi(o.size??o[4]); const filled=bi(o.filled??o[5]); return {orderId:bi(o.orderId??o[0]),user,marketKey:String(o.marketKey??o[2]??mk??'').toLowerCase(),intent:Number(o.intent??o[3]??0),size,filled,askPrice:bi(o.askPrice??o[6]),expiry:bi(o.expiry??o[7]),timestamp:bi(o.timestamp??o[8]),active:size>filled,feeToken:addr(o.feeToken??ethers.ZeroAddress)}}
 async latestTimestamp():Promise<bigint>{const p=await this.wallet.getEthersProvider(); if(!p)return BigInt(Math.floor(Date.now()/1000)); const b=await p.getBlock('latest'); return BigInt(b?.timestamp??Math.floor(Date.now()/1000))}
 async getMarketKeys():Promise<string[]>{const c=await this.mc(); if(!c)return[]; try{return ((await c['getMarketKeys']())??[]).map((x:any)=>String(x).toLowerCase())}catch{return[]}}
 async getMarket(mk:string):Promise<MarginMarket|null>{const c=await this.mc(); if(!c)return null; try{const m=this.mapMarket(await c['getMarket'](mk)); if(m){try{m.openInterest=bi(await c['marketOpenInterest'](mk))}catch{m.openInterest=0n} try{const pm=await this.pm(); if(pm&&m.oracle){const p=await pm['getOraclePrice'](m.oracle,4); m.latestOraclePrice=bi(p.price??p[0]); m.latestOraclePriceDecimals=Number(p.priceDecimals??p[1]??m.oraclePriceDecimals??18); m.latestOracleTimestamp=bi(p.timestamp??p[2]); m.latestOracleStatus=Number(p.status??p[3]??0)}}catch{}} return m}catch{return null}}
 async getOpenOrders(mk:string,bid:boolean):Promise<MarginOrder[]>{const c=await this.ob(); if(!c)return[]; try{return ((await c['getOpenOrders'](mk,bid))??[]).map((x:any)=>this.mapOrder(x,mk)).filter((x:MarginOrder|null):x is MarginOrder=>!!x&&x.active&&x.size>x.filled)}catch{return[]}}
 async getRequiredMargin(mk:string,size:bigint):Promise<bigint>{const c=await this.mc(); if(!c||size<=0n)return 0n; try{return bi(await c['getRequiredMargin'](mk,size))}catch{return 0n}}
 async getPayoutPerUnit(mk:string):Promise<bigint>{const c=await this.mc(); if(!c)return 0n; try{return bi(await c['getPayoutPerUnit'](mk))}catch{return 0n}}
 async getHolderPosition(mk:string,acct:string):Promise<MarginHolderPosition>{const c=await this.mc(); if(!c||!acct)return{size:0n,claimed:0n,reserved:0n}; try{const r=await c['holders'](mk,acct); return{size:bi(r.size??r[0]),claimed:bi(r.claimed??r[1]),reserved:bi(r.reserved??r[2])}}catch{return{size:0n,claimed:0n,reserved:0n}}}
 async getWriterPosition(mk:string,acct:string):Promise<MarginWriterPosition>{const c=await this.mc(); if(!c||!acct)return{size:0n,allocated:0n,lockedMargin:0n,paidOut:0n,reserved:0n}; try{const r=await c['writers'](mk,acct); return{size:bi(r.size??r[0]),allocated:bi(r.allocated??r[1]),lockedMargin:bi(r.lockedMargin??r[2]),paidOut:bi(r.paidOut??r[3]),reserved:bi(r.reserved??r[4])}}catch{return{size:0n,allocated:0n,lockedMargin:0n,paidOut:0n,reserved:0n}}}
 async getMarketOpenInterest(mk:string):Promise<bigint>{const c=await this.mc(); if(!c)return 0n; try{return bi(await c['marketOpenInterest'](mk))}catch{return 0n}}
}
