import { ContractName } from './contract-names';

export const IGNITION_ARTIFACT_MAP = {
  SethxToken: 'FeeManagerModule#SethxToken',
  MockERC1155: 'MockERC1155Module#MockERC1155',
  MockERC20A: 'MockERC20AModule#MockERC20A',
  MockERC20B: 'MockERC20BModule#MockERC20B',
  MockERC20C: 'MockERC20CModule#MockERC20C',
  MockERC721: 'MockERC721Module#MockERC721',
  MockOracle: 'MockOracleModule#MockOracle',
  BtcUsdChainlinkOracle: 'ChainlinkMarketOraclesModule#BtcUsdChainlinkOracle',
  EthUsdChainlinkOracle: 'ChainlinkMarketOraclesModule#EthUsdChainlinkOracle',
  LinkUsdChainlinkOracle: 'ChainlinkMarketOraclesModule#LinkUsdChainlinkOracle',
  SethxFeeConversionOracle: 'SethxFeeConversionOracleModule#SethxFeeConversionOracle',
  SethxTimelock: 'TimelockModule#SethxTimelock',
  TimelockControllerWrapper: 'TimelockModule#SethxTimelock',
  QuoteCollateralOracle: 'ValuationMockOraclesModule#QuoteCollateralOracle',
  PriceManager: 'PriceManagerModule#PriceManager',
  AccountRegistry: 'RegistryModule#AccountRegistry',
  TreasuryAuthority: 'TreasuryAuthorityModule#TreasuryAuthority',
  FeeManager: 'FeeManagerModule#FeeManager',
  ProtocolTreasury: 'ProtocolTreasuryModule#ProtocolTreasury',
  SethxVault: 'VaultModule#SethxVault',
  AccountFactory: 'AccountFactoryModule#AccountFactory',
  BinaryMarginOptionContract:
    'BinaryMarginOptionContractModule#BinaryMarginOptionContract',
  FuturesContract: 'FuturesContractModule#FuturesContract',
  SethxGovernor: 'GovernorModule#SethxGovernor',
  LendingContract: 'LendingContractModule#LendingContract',
  MarginOptionContract: 'MarginOptionContractModule#MarginOptionContract',
  NFTSpotOrderBook: 'NFTSpotCoreModule#NFTSpotOrderBook',
  OptionContract: 'OptionsCoreModule#OptionContract',
  TokenSpotOrderBook: 'SpotCoreModule#TokenSpotOrderBook',
  TreasuryPaymentsModule: 'TreasuryPaymentsModuleModule#TreasuryPaymentsModule',
  TreasuryVaultModule: 'TreasuryVaultModuleModule#TreasuryVaultModule',
  BinaryMarginOptionsOrderBook:
    'BinaryMarginOptionsOrderBookModule#BinaryMarginOptionsOrderBook',
  FuturesOrderBook: 'FuturesOrderBookModule#FuturesOrderBook',
  LendingOrderBook: 'LendingOrderBookModule#LendingOrderBook',
  MarginOptionsOrderBook: 'MarginOptionsOrderBookModule#MarginOptionsOrderBook',
  OptionsOrderBook: 'OptionsCoreModule#OptionsOrderBook',
  SettlementManager: 'SettlementManagerModule#SettlementManager',
  TreasuryTradeModule: 'TreasuryTradeModuleModule#TreasuryTradeModule',
  FuturesValuationAdapter: 'ValuationAdaptersModule#FuturesValuationAdapter',
  ValuationModule: 'ValuationModuleModule#ValuationModule',
  LiquidationEngine: 'LiquidationEngineModule#LiquidationEngine',
  PassiveFuturesSnapshotPublisher:
    'PassiveFuturesSnapshotPublisherModule#PassiveFuturesSnapshotPublisher',
  PassiveFuturesPoolFactory:
    'PassiveFuturesPoolFactoryModule#PassiveFuturesPoolFactory',
  RiskModule: 'RiskModuleModule#RiskModule',
  OptionsValuationAdapter: 'ValuationAdaptersModule#OptionsValuationAdapter',
  LendingAccountFactory: 'LendingAccountFactoryModule#LendingAccountFactory',
} as const satisfies Record<ContractName, string>;
