import { Injectable, computed, inject, resource, signal } from '@angular/core';
import { stableComputed, stableResourceValue, structuralEqual } from '../../../core/signals/stable-resource';
import { TriggerService } from '../trigger.service';
import { TradeSettingsService } from '../trade-settings.service';
import { MarketTimeService } from '../market-time.service';
import { norm } from '../../../core/tokens/token-normalize';
import { MarginHolderPosition, MarginMarket, MarginOptionsReadService, MarginOrder, MarginWriterPosition } from '../../onchain/contracts/margin-options-read.service';
import { MarginOptionsFormatService } from './margin-options-format.service';
export type MarginMarketRow={marketKey:string;market:MarginMarket;orderCount:bigint;myOrderCount:bigint;totalRemaining:bigint;requiredMarginForOne:bigint};
export type MarginLadderRow={orderId:bigint;side:'bid'|'ask';isMine:boolean;order:MarginOrder};
export type MarginPositionRow={marketKey:string;market:MarginMarket;holder:MarginHolderPosition;writer:MarginWriterPosition;holderAvailable:bigint;writerAvailable:bigint;openInterest:bigint;payoutPerUnit:bigint;settlementStatus:string;canBuy:boolean;canWrite:boolean;canSellHolder:boolean;canSellWriter:boolean;canClaim:boolean;canReclaim:boolean;buyHint:string;writeHint:string;sellHolderHint:string;sellWriterHint:string;claimHint:string;reclaimHint:string};
@Injectable({providedIn:'root'})
export class MarginOptionsOrderBookStore{
 private readonly reads=inject(MarginOptionsReadService); private readonly trigger=inject(TriggerService); private readonly settings=inject(TradeSettingsService); private readonly marketTime=inject(MarketTimeService); private readonly fmt=inject(MarginOptionsFormatService);
 readonly selectedMarketKey=signal<string|null>(null); readonly selectedPositionKey=signal<string|null>(null); readonly activeView=signal<'markets'|'orders'|'positions'|'my-orders'>('markets'); readonly marketFetchLimit=signal(100); readonly marketOffset=signal(0); readonly marketLimit=signal(25); readonly marketSearch=signal(''); readonly marketsWithMyOrdersOnly=signal(false); readonly myOrdersOnly=signal(false); readonly activeAccount=computed(()=>norm(this.settings.selectedAccountId()??''));
 tokenLabel=(a:string)=>this.fmt.tokenLabel(a); formatAmount=(v:bigint,t:string)=>this.fmt.formatAmount(v,t); formatQuantity=(v:bigint|null|undefined)=>this.fmt.formatQuantity(v,18); formatEth=(v:bigint)=>this.fmt.formatEth(v); formatStrike=(v:bigint)=>this.fmt.formatStrike(v); formatOraclePrice=(v:bigint|null|undefined,d:number|null|undefined)=>this.fmt.formatOraclePrice(v,d); formatBpsPercent=(v:bigint|null|undefined)=>this.fmt.formatBpsPercent(v); formatPrice=(v:bigint,t?:string|null)=>this.fmt.formatPrice(v,t); optionTypeLabel=(t:number)=>this.fmt.optionTypeLabel(t); intentLabel=(t:number)=>this.fmt.intentLabel(t); marketTitle=(m:MarginMarket)=>this.fmt.marketTitle(m);
 private readonly fillAmounts=signal<Record<string,string>>({}); fillAmountByOrderId(id:bigint):string{return this.fillAmounts()[id.toString()]??''} setFillAmount(id:bigint,v:string):void{const key=id.toString(); const value=String(v??''); this.fillAmounts.update(current=>({...current,[key]:value}))}
 private readonly _marketsRes=resource<MarginMarketRow[],{tick:number;limit:number;account:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),limit:this.marketFetchLimit(),account:this.activeAccount()}),loader:async({params})=>{const keys=await this.reads.getMarketKeys(); const rows:MarginMarketRow[]=[]; const mine=(o:MarginOrder)=>!!params.account&&norm(o.user)===params.account; for(const k of keys.slice(0,params.limit)){const market=await this.reads.getMarket(k); if(!market||!market.active)continue; const [bids,asks,requiredMarginForOne]=await Promise.all([this.reads.getOpenOrders(k,true),this.reads.getOpenOrders(k,false),this.reads.getRequiredMargin(k,10n**BigInt(market.paymentTokenDecimals||18)).catch(()=>0n)]); const orders=[...bids,...asks]; const totalRemaining=orders.reduce((s,o)=>s+(o.size>o.filled?o.size-o.filled:0n),0n); rows.push({marketKey:k,market,orderCount:BigInt(orders.length),myOrderCount:BigInt(orders.filter(mine).length),totalRemaining,requiredMarginForOne})} rows.sort((a,b)=>Number(b.orderCount-a.orderCount)); return rows}});
 private readonly _stableMarkets=stableResourceValue(()=>this._marketsRes.value(), [] as MarginMarketRow[], {resetKey:()=>this.marketFetchLimit(), equal: structuralEqual}); readonly activeMarkets=stableComputed(()=>this._stableMarkets()); readonly filteredMarkets=stableComputed(()=>{const q=this.marketSearch().trim().toLowerCase(); const onlyMine=this.marketsWithMyOrdersOnly(); const positionMarkets=new Set(this.myPositions().map((p)=>String(p.marketKey??'').toLowerCase())); let list=this.activeMarkets().filter((m)=>this.marketTime.hasOpenOptionWindow(m.market)||positionMarkets.has(String(m.marketKey??'').toLowerCase())||(m.myOrderCount??0n)>0n); if(q){list=list.filter((m)=>[this.marketTitle(m.market),m.marketKey,m.market?.ticker,this.tokenLabel(m.market?.paymentToken)].some((v)=>String(v??'').toLowerCase().includes(q)));} if(onlyMine){list=list.filter((m)=>(m.myOrderCount??0n)>0n);} return list;}); readonly visibleMarkets=stableComputed(()=>{const start=Math.max(0,Number(this.marketOffset()||0)); const limit=Math.max(1,Number(this.marketLimit()||25)); return this.filteredMarkets().slice(start,start+limit);}); selectMarket(k:string):void{this.selectedMarketKey.set(String(k??'').toLowerCase());this.clearSelectedPosition()} clearMarket():void{this.selectedMarketKey.set(null)} selectPosition(k:string):void{this.selectedPositionKey.set(String(k??'').toLowerCase())} clearSelectedPosition():void{this.selectedPositionKey.set(null)} readonly selectedMarket=computed(()=>this.activeMarkets().find(m=>m.marketKey===this.selectedMarketKey())??null);
 private readonly _ladderRes=resource<{bids:MarginLadderRow[];asks:MarginLadderRow[]},{tick:number;marketKey:string|null;account:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),marketKey:this.selectedMarketKey(),account:this.activeAccount()}),loader:async({params})=>{if(!params.marketKey)return{bids:[],asks:[]}; const [br,ar]=await Promise.all([this.reads.getOpenOrders(params.marketKey,true),this.reads.getOpenOrders(params.marketKey,false)]); const mine=(o:MarginOrder)=>!!params.account&&norm(o.user)===params.account; return {bids:br.map(order=>({orderId:order.orderId,side:'bid' as const,isMine:mine(order),order})).sort((a,b)=>Number(b.order.askPrice-a.order.askPrice)),asks:ar.map(order=>({orderId:order.orderId,side:'ask' as const,isMine:mine(order),order})).sort((a,b)=>Number(a.order.askPrice-b.order.askPrice))}}});
 private readonly _stableLadder=stableResourceValue(()=>this._ladderRes.value(), {bids: [] as MarginLadderRow[], asks: [] as MarginLadderRow[]}, {resetKey:()=>this.selectedMarketKey(), equal: structuralEqual}); readonly bids=stableComputed(()=>{const rows=this._stableLadder().bids; return this.myOrdersOnly()?rows.filter((r)=>r.isMine):rows}); readonly asks=stableComputed(()=>{const rows=this._stableLadder().asks; return this.myOrdersOnly()?rows.filter((r)=>r.isMine):rows}); readonly bestBid=computed(()=>this.bids()[0]?.order.askPrice??null); readonly bestAsk=computed(()=>this.asks()[0]?.order.askPrice??null); readonly spread=computed(()=>{const b=this.bestBid(); const a=this.bestAsk(); if(b===null||a===null||a<b)return null; return a-b});
 private readonly _positionsRes=resource<MarginPositionRow[],{tick:number;account:string;markets:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),account:this.activeAccount(),markets:this.activeMarkets().map(m=>m.marketKey).join('|')}),loader:async({params})=>{if(!params.account)return[]; const now=await this.reads.latestTimestamp(); const rows:MarginPositionRow[]=[]; for(const row of this.activeMarkets()){const [holder,writer,openInterest,payoutPerUnit]=await Promise.all([this.reads.getHolderPosition(row.marketKey,params.account),this.reads.getWriterPosition(row.marketKey,params.account),this.reads.getMarketOpenInterest(row.marketKey),this.reads.getPayoutPerUnit(row.marketKey)]); const holderAvailable=holder.size>holder.claimed+holder.reserved?holder.size-holder.claimed-holder.reserved:0n; const writerAvailable=writer.size>writer.reserved?writer.size-writer.reserved:0n; if(holderAvailable<=0n&&writerAvailable<=0n&&writer.lockedMargin<=writer.paidOut)continue; const marketOpen=row.market.active&&!row.market.settled&&now<row.market.expiry; const canClaim=holderAvailable>0n&&row.market.settled; const canReclaim=writer.lockedMargin>writer.paidOut&&row.market.settled&&openInterest===0n; rows.push({marketKey:row.marketKey,market:row.market,holder,writer,holderAvailable,writerAvailable,openInterest,payoutPerUnit,settlementStatus:row.market.settled?'Settled':now>=row.market.expiry?'Expired, awaiting settlement':'Open',canBuy:marketOpen,canWrite:marketOpen,canSellHolder:holderAvailable>0n&&marketOpen,canSellWriter:writerAvailable>0n&&marketOpen,canClaim,canReclaim,buyHint:marketOpen?'Buy additional holder size in this market':'Market is expired, settled, or closed',writeHint:marketOpen?'Write fresh option size and lock margin':'Market is expired, settled, or closed',sellHolderHint:holderAvailable>0n?(marketOpen?'Sell holder size before expiry':'Holder sale closes at expiry'):'No holder size available',sellWriterHint:writerAvailable>0n?(marketOpen?'Sell writer size before expiry':'Writer sale closes at expiry'):'No writer size available',claimHint:canClaim?'Claim settled payout':row.market.settled?'No holder size available to claim':'Available after settlement',reclaimHint:canReclaim?'Reclaim residual writer margin':row.market.settled?'Waiting for open interest to clear or no reclaimable margin':'Available after settlement'})} return rows}});
 
 private readonly _myOrdersRes=resource<MarginLadderRow[],{tick:number;account:string;markets:string}>({params:()=>({tick:this.trigger.optionsOrderbookTick(),account:this.activeAccount(),markets:this.activeMarkets().map(m=>m.marketKey).join('|')}),loader:async({params})=>{if(!params.account)return[]; const mine=(o:MarginOrder)=>norm(o.user)===params.account; const rows:MarginLadderRow[]=[]; for(const m of this.activeMarkets()){const [bids,asks]=await Promise.all([this.reads.getOpenOrders(m.marketKey,true),this.reads.getOpenOrders(m.marketKey,false)]); rows.push(...bids.filter(mine).map(order=>({orderId:order.orderId,side:'bid' as const,isMine:true,order}))); rows.push(...asks.filter(mine).map(order=>({orderId:order.orderId,side:'ask' as const,isMine:true,order})))} rows.sort((a,b)=>Number((b.orderId??0n)-(a.orderId??0n))); return rows}});
 private readonly _stableMyOrders=stableResourceValue(()=>this._myOrdersRes.value(), [] as MarginLadderRow[], {resetKey:()=>this.activeAccount(), equal: structuralEqual}); readonly myOrders=stableComputed(()=>this._stableMyOrders());
 private readonly _stablePositions=stableResourceValue(()=>this._positionsRes.value(), [] as MarginPositionRow[], {resetKey:()=>this.activeAccount(), equal: structuralEqual}); readonly myPositions=stableComputed(()=>this._stablePositions()); readonly selectedPosition=computed(()=>this.myPositions().find(p=>p.marketKey===this.selectedPositionKey())??null);
}
